version: '3.1'

services:
  image:
    build: .
    command: python nutrition_service.py
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 0
      PORT: 3000
      # dev
      # PUBLIC_KEY: ${PUBLIC_KEY_PATH}

      # prod
      PUBLIC_KEY: ${PUBLIC_KEY_STR}
    volumes:
      - 'nutrition_fs:/nutrition/uploads'


volumes:
  image_fs:
    external: true