version: '3.1'

services:
  image:
    build: .
    command: python image_service.py
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 0
      PORT: 3000
      # dev
      # PUBLIC_KEY: ${PUBLIC_KEY_PATH}

      # prod
      PUBLIC_KEY: ${PUBLIC_KEY_STR}
    volumes:
      - 'image_fs:/images/uploads'


volumes:
  image_fs:
    external: true